name: Cache Manually
run-name: Cache Manually

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 22.13.1

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      lockfile_hash: ${{ steps.compute_lockfile_hash.outputs.lockfile_hash }}
    name: Cache Manually
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Compute package-lock.json hash
        id: compute_lockfile_hash
        run: echo "lockfile_hash=${{hashFiles('package-lock.json')}}" >> "$GITHUB_OUTPUT"

      - name: Restore npm cache
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-${{ steps.compute_lockfile_hash.outputs.lockfile_hash }}

      - if: ${{ steps.npm-cache.outputs.cache-hit == 'true' }}
        name: Log cache status
        run: echo "using cached npm"

      - name: Install dependencies
        run: npm ci --verbose


