name: Deploy
run-name: Deploy

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 22.13.1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install Deps
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Create Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'app_dist_folder'
          path: ./dist
          overwrite: true
          retention-days: 1
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Dist Artifact
        uses: actions/download-artifact@v4
        with:
          name: 'app_dist_folder'

      - name: Deploy To Vercel
        id: deploy-step
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-project-name: 'ci-cd-frontend'

      - name: Deploy Info
        run: |
          echo "preview-url - ${{ steps.deploy-step.outputs.preview-url }}"
          echo "preview-name - ${{ steps.deploy-step.outputs.preview-name }}"

  cleanup:
    needs:
      - build
      - deploy
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: 'app_dist_folder'
          failOnError: false