name: Run Tests
run-name: Run My JS Tests
on:
  pull_request:
    branches:
      - main
env:
  NODE_VERSION: 22.13.1
jobs:
  Check_Test_Files:
    name: Check Test Files Exists
    runs-on: ubuntu-latest
    env:
      TEST_FOLDER_PATH: ./src/scripts/test/
    strategy:
      matrix:
        file: [ unit.js, e2e.js]
    steps:
      - name: Make script executable
        run: chmod +x ./workflow_scripts/check-file.sh

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Test Files Are Exists
        run: |
          FILE_PATH="${{ env.TEST_FOLDER_PATH }}${{ matrix.file }}"
          ./workflow_scripts/check-file.sh "$FILE_PATH"

      - run: echo "Success"
  Run_Tests:
    name: Run fake tests
    needs: Check_Test_Files
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run unit test
        run: node ./src/scripts/test/unit.js

      - name: Run e2e test
        run: node ./src/scripts/test/e2e.js

      - name: Workflow completed
        run: echo "🎉 All tests passed successfully!"

      - name: Force success exit
        run: exit 0