name: Cache Built In
run-name: Cache Built In

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 22.13.1

jobs:
  test:
    runs-on: ubuntu-latest
    name: Cache Built In
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci --verbose
